### PR TITLE
Add SSL validation feature for uptime tests

### PR DESCRIPTION
**Pull request by ivanschwarz**
I accidentally closed #26, and It seems I'm not able to reopen it again, so here is the same functionality in a new PR.

I've updated the client dependency using following commands (as per #25):
```
$ GO111MODULE=on go get github.com//DreamItGetIT/statuscake@master
$ GO111MODULE=on go mod tidy
$ GO111MODULE=on go mod vendor
```

Original summary:
> Addresses #16.
>
> I've tried to be as consistent as possible with [StatusCake API](https://www.statuscake.com/api/) docs in terms of naming, but I'm happy to change things according to your requirements.
>
> Note that API expects the `EnableSSLAlert` property for create and update requests, but returns the `EnableSSLWarning` property for get requests even though ultimately it's the same property. I'm not sure why.
>
> Acceptance tests are passing.
>
> Please let me know if there are changes required in order for this feature to be merged.

### CODE REVIEW

**Comment by jcalonso** [comment]
@appilon @matschaffer are you happy to merge this PR? is anything else needed for the 1.0 release?
Thanks :)

**Comment by matschaffer** [comment]
Yep, looks good. Only think I see outstanding PR-wise is the importer https://github.com/terraform-providers/terraform-provider-statuscake/pull/36

Hopefully I can test it this weekend, but if it all works it could be nice to get in for 1.0

**Comment by matschaffer** [comment]
Found some time to test the importer so merged that. Still need to give a full test of what's been merged and do changelog updates. @jcalonso if you or anyone would like to help with updating https://github.com/terraform-providers/terraform-provider-statuscake/blob/master/CHANGELOG.md that'd be awesome. 

I _thought_ we needed the `GH-8` format, but looks like https://github.com/terraform-providers/terraform-provider-aws/edit/master/CHANGELOG.md is just using `#NUMBER` now.

@paultyng can you help confirm the latest CHANGELOG format expectations?

**Comment by jcalonso** [comment]
Hey @matschaffer, I have updated the changelog in #39. Let me know if I missed something or the format needs to be different. :slightly_smiling_face:

**Comment by paultyng** [comment]
The release script automatically updates the `[GH-8]` syntax to the links, but if you add the links manually it also works. We hope to make the changelog generation a bit nicer soon, have some internal pilots running.

**Pull request merged**
