### PR TITLE
Upgrade to 0.12

### PR DESCRIPTION
**Pull request by ndench**
I followed the steps defined in the [terraform providers upgrade guide](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html), namely:

```
go get github.com/hashicorp/terraform@v0.12.0
go mod tidy
go mod vendor
```

Then ran the tests. `make test` passes successfully, however I'm running into problems with `make testacc`:

```
$ STATUSCAKE_USERNAME=<username> STATUSCAKE_APIKEY=<apikey> make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?       github.com/terraform-providers/terraform-provider-statuscake    [no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccStatusCake_basic
--- FAIL: TestAccStatusCake_basic (2.60s)
    testing.go:568: Step 0 error: errors during apply:
        
        Error: Error creating StatusCake Test: HTTP error: 400 - 400 Bad Request
        
          on /tmp/tf-test117348077/main.tf line 2:
          (source code not available)
        
        
=== RUN   TestAccStatusCake_tcp
--- FAIL: TestAccStatusCake_tcp (1.15s)
    testing.go:568: Step 0 error: errors during apply:
        
        Error: Error creating StatusCake Test: HTTP error: 400 - 400 Bad Request
        
          on /tmp/tf-test801965479/main.tf line 2:
          (source code not available)
        
        
=== RUN   TestAccStatusCake_withUpdate
--- FAIL: TestAccStatusCake_withUpdate (1.12s)
    testing.go:568: Step 0 error: errors during apply:
        
        Error: Error creating StatusCake Test: HTTP error: 400 - 400 Bad Request
        
          on /tmp/tf-test241732209/main.tf line 2:
          (source code not available)
        
        
FAIL
FAIL    github.com/terraform-providers/terraform-provider-statuscake/statuscake 4.881s
make: *** [GNUmakefile:17: testacc] Error 1
```

I'm not not sure where to even start to fix this, I've just been trying to follow what [other providers did](https://github.com/terraform-providers/terraform-provider-archive/pull/38).

If someone could point me in the right direction that would be much appreciated.

Closes: #31

### CODE REVIEW

**Comment by jcalonso** [comment]
Any plans to release this soon? :smiley:

**Comment by jcalonso** [comment]
@ndench Fixed the issue and made a pull request against your branch: https://github.com/ndench/terraform-provider-statuscake/pull/1
Test pass but you need to provide the `STATUSCAKE_TEST_CONTACT_GROUP_ID` env

**Comment by ndench** [comment]
The functional tests are passing now:
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?       github.com/terraform-providers/terraform-provider-statuscake    [no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestAccStatusCake_basic
--- PASS: TestAccStatusCake_basic (4.28s)
=== RUN   TestAccStatusCake_tcp
--- PASS: TestAccStatusCake_tcp (5.02s)
=== RUN   TestAccStatusCake_withUpdate
--- PASS: TestAccStatusCake_withUpdate (8.06s)
PASS
ok      github.com/terraform-providers/terraform-provider-statuscake/statuscake 17.362s
```

This is ready to be merged :smile:

**Comment by jcalonso** [comment]
Kindly pinging @appilon and/or @matschaffer could review this pull request?
Happy to help with any changes required to merge this :) 
Cheers

**Comment by matschaffer** [comment]
Any objections if I just merge it without running it myself? Looks okay, tests pass. We can release until someone sorts out backward compat on the contact groups stuff anyway

**Comment by jcalonso** [comment]
@matschaffer What is the problem with the contact groups?

**Comment by matschaffer** [comment]
What's in master isn't backward compatible with the current release's resource model. I wasn't able to get it working and thought a breaking change would be okay given the 0.x version status

**Comment by ndench** [comment]
@matschaffer no objections from me. Is there anything I can help with to get a release out?

**Comment by matschaffer** [comment]
Good enough for me. Last time I requested a release the breaking change from contact_id to contact_groups was flagged as a blocker. If you're able to make that backward compatible that should unblock release afaik

**Comment by jcalonso** [comment]
@matschaffer @ndench Made the contact_group backward compatible, please have a look and give me feedback if I missed anything. 
https://github.com/terraform-providers/terraform-provider-statuscake/pull/34

**Pull request merged**
