### PR TITLE
Add `enable_ssl_alert` option, and small fixes

### PR DESCRIPTION
**Pull request by nh2**
Implements the **Validate SSL** option in tests asked for in #16 (note this just a simple checkbox and is NOT StatusCakes sophisticated SSL verification feature asked for in #6 ~and provided in PR #35~):

image

Made possible by @ivanschwarz in https://github.com/DreamItGetIT/statuscake/pull/41.

### CODE REVIEW

**Comment by nh2** [comment]
I've made a prebuilt binary available here: https://github.com/nh2/terraform-provider-statuscake/releases/tag/nh2fixes-enable_ssl_alert-2019-06-20-2

**Comment by tdmalone** [comment]
Isn’t this the same as #35? I believe #35 is for the validate SSL option in uptime tests (not the separate SSL Tests) as well.

**Comment by nh2** [comment]
Oops, you are right. I somehow missed that yesterday. Oh well.

The PRs look pretty similar, so I don't care which one to merge. But I also have a couple extra commits in here that should probably be cherry-picked.

**Comment by matschaffer** [comment]
Closing in favor of https://github.com/terraform-providers/terraform-provider-statuscake/pull/35

**Comment by nh2** [comment]
> But I also have a couple extra commits in here that should probably be cherry-picked.

I put that in a separate PR #40.

**Pull request closed without merging**
