### PR TITLE
Add support back for contact_id and mark it as deprecated

### PR DESCRIPTION
**Pull request by jcalonso**
This makes the contact_group change backwards compatible

### CODE REVIEW

**Comment by matschaffer** [comment]
Thanks so much ❤️

**Comment by jcalonso** [comment]
Updated documentation

**Comment by matejvelikonja** [comment]
can we merge this and make a new release?

**Comment by matschaffer** [comment]
Might be good to get https://github.com/terraform-providers/terraform-provider-statuscake/pull/26 in before release as well

**Pull request merged**
